name: Deploy Docker Container

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: |
          docker build -t zendoc.io:latest .

      - name: Stop existing container
        run: |
          docker stop zendoc.io || true
          docker rm zendoc.io || true
        continue-on-error: true

      - name: Deploy container
        run: |
          docker run -d --name zendoc.io \
            -p 4000:3000 \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASS="${{ secrets.DB_PASS }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_DB="${{ secrets.DB_DB }}" \
            -e ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
            -e SMTP_HOST="${{ secrets.SMTP_HOST }}" \
            -e SMTP_PORT="${{ secrets.SMTP_PORT }}" \
            -e SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
            -e SMTP_USER="${{ secrets.SMTP_USER }}" \
            -e SMTP_FROM="${{ secrets.SMTP_FROM }}" \
            --restart unless-stopped \
            zendoc.io:latest
